from torch import nn
from model import GraphClassifier
import torch
import os
import json
import argparse
import random
import numpy as np
from sklearn.metrics import average_precision_score
from torch_geometric.loader import DataLoader





def load_manifest(manifest_path):
    with open(manifest_path, 'r', encoding='utf-8') as f:
        manifest = json.load(f)

    base_dir = os.path.dirname(os.path.abspath(manifest_path))
    files = manifest.get('files', [])
    batch_paths = [os.path.join(base_dir, fname) for fname in files]
    return manifest, batch_paths


def iter_graph_batches(manifest_path):
    """Yield graph lists one serialized batch at a time (RAM-safe)."""
    _, batch_paths = load_manifest(manifest_path)
    for p in batch_paths:
        payload = torch.load(p, map_location='cpu', weights_only=False)
        graphs = payload['graphs'] if isinstance(payload, dict) and 'graphs' in payload else payload
        yield p, graphs


def iter_graph_batches_from_paths(batch_paths):
    """Yield graph lists one serialized batch at a time from explicit file paths."""
    for p in batch_paths:
        payload = torch.load(p, map_location='cpu', weights_only=False)
        graphs = payload['graphs'] if isinstance(payload, dict) and 'graphs' in payload else payload
        yield p, graphs


def split_batch_files(batch_paths, val_ratio=0.2, seed=42):
    """Split serialized graph-batch files into train and validation subsets."""
    if val_ratio <= 0.0 or len(batch_paths) <= 1:
        return list(batch_paths), []

    shuffled = list(batch_paths)
    rng = random.Random(seed)
    rng.shuffle(shuffled)

    val_count = max(1, int(len(shuffled) * val_ratio))
    if val_count >= len(shuffled):
        val_count = len(shuffled) - 1

    val_paths = shuffled[:val_count]
    train_paths = shuffled[val_count:]
    return train_paths, val_paths


def compute_average_precision(y_true, y_score):
    """Return AP score or NaN when AP cannot be computed robustly."""
    if len(y_true) == 0:
        return float('nan')
    unique_labels = np.unique(y_true)
    if unique_labels.size < 2:
        return float('nan')
    return float(average_precision_score(y_true, y_score))


def evaluate_from_batch_paths(model, batch_paths, criterion, batch_size, device):
    """Evaluate loss and AP over serialized graph batches using DataLoaders."""
    model.eval()
    total_loss = 0.0
    total_items = 0
    all_labels = []
    all_scores = []

    with torch.no_grad():
        for batch_file, graphs in iter_graph_batches_from_paths(batch_paths):
            if not graphs:
                continue

            loader = DataLoader(graphs, batch_size=batch_size, shuffle=False)
            for pyg_batch in loader:
                pyg_batch = pyg_batch.to(device)
                y = pyg_batch.y.view(-1).long()
                logits = model(pyg_batch)
                loss = criterion(logits, y)

                probs = torch.softmax(logits, dim=1)[:, 1]
                bs = int(y.shape[0])

                total_loss += loss.item() * bs
                total_items += bs
                all_labels.extend(y.detach().cpu().numpy().tolist())
                all_scores.extend(probs.detach().cpu().numpy().tolist())

            del loader
            del graphs
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

    avg_loss = (total_loss / total_items) if total_items > 0 else float('nan')
    ap = compute_average_precision(np.array(all_labels), np.array(all_scores))
    return avg_loss, ap, total_items


class EarlyStopping:
    def __init__(self, patience=10, min_delta=0.0):
        self.patience = patience
        self.min_delta = min_delta
        self.best_score = -float('inf')
        self.counter = 0

    def step(self, score):
        if score > self.best_score + self.min_delta:
            self.best_score = score
            self.counter = 0
        else:
            self.counter += 1
        return self.counter >= self.patience



def train_from_manifest(manifest_path, epochs=5, batch_size=4, lr=1e-4,
                        hidden_dim=256, num_heads=4, dropout=0.5,
                        num_classes=2, use_gat=True, device=None,
                        early_stopping_patience=None,
                        early_stopping_min_delta=0.0,
                        early_stopping_min_epochs=1,
                        val_manifest_path=None,
                        val_ratio=0.2,
                        split_seed=42,
                        save_best_model_path=None):
    """
    Train directly from batched graph files generated by binding_site_graph.py.
    Processes one graph-batch file at a time to keep memory usage low.
    """
    if device is None:
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    else:
        device = torch.device(device)

    model = GraphClassifier(
        node_dim=1280,
        hidden_dim=hidden_dim,
        num_attention_heads=num_heads,
        dropout=dropout,
        num_classes=num_classes,
        use_gat=use_gat,
    ).to(device)

    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    manifest, all_batch_paths = load_manifest(manifest_path)
    print(f"Loaded manifest with {len(all_batch_paths)} graph-batch files")
    print(f"Manifest expected graphs: {manifest.get('num_graphs', 'unknown')}")

    if val_manifest_path:
        _, val_batch_paths = load_manifest(val_manifest_path)
        train_batch_paths = all_batch_paths
        print(f"Validation manifest loaded with {len(val_batch_paths)} graph-batch files")
    else:
        train_batch_paths, val_batch_paths = split_batch_files(
            all_batch_paths,
            val_ratio=val_ratio,
            seed=split_seed,
        )
        print(
            "Using internal split from training manifest: "
            f"train_files={len(train_batch_paths)}, val_files={len(val_batch_paths)}"
        )

    use_early_stopping = (
        early_stopping_patience is not None and early_stopping_patience > 0
    )
    early_stopper = None
    if use_early_stopping:
        early_stopper = EarlyStopping(
            patience=early_stopping_patience,
            min_delta=early_stopping_min_delta
        )
        print(
            "Early stopping enabled: "
            f"patience={early_stopping_patience}, "
            f"min_delta={early_stopping_min_delta}, "
            f"min_epochs={early_stopping_min_epochs}"
        )

    best_val_ap = -float('inf')
    best_epoch = None

    for epoch in range(1, epochs + 1):
        model.train()
        epoch_loss = 0.0
        epoch_items = 0

        all_train_labels = []
        all_train_scores = []

        for batch_file, graphs in iter_graph_batches_from_paths(train_batch_paths):
            if not graphs:
                continue

            loader = DataLoader(graphs, batch_size=batch_size, shuffle=True)
            for pyg_batch in loader:
                pyg_batch = pyg_batch.to(device)
                y = pyg_batch.y.view(-1).long()

                optimizer.zero_grad(set_to_none=True)
                logits = model(pyg_batch)
                loss = criterion(logits, y)
                loss.backward()
                optimizer.step()

                probs = torch.softmax(logits.detach(), dim=1)[:, 1]

                bs = int(y.shape[0])
                epoch_loss += loss.item() * bs
                epoch_items += bs
                all_train_labels.extend(y.detach().cpu().numpy().tolist())
                all_train_scores.extend(probs.cpu().numpy().tolist())

            del loader
            del graphs


        avg_loss = (epoch_loss / epoch_items) if epoch_items > 0 else float('nan')
        train_ap = compute_average_precision(
            np.array(all_train_labels),
            np.array(all_train_scores),
        )

        val_loss = float('nan')
        val_ap = float('nan')
        val_items = 0
        if val_batch_paths:
            val_loss, val_ap, val_items = evaluate_from_batch_paths(
                model=model,
                batch_paths=val_batch_paths,
                criterion=criterion,
                batch_size=batch_size,
                device=device,
            )

        print(
            f"Epoch {epoch}/{epochs} - "
            f"train_loss: {avg_loss:.6f} - train_AP: {train_ap:.6f} - train_samples: {epoch_items} - "
            f"val_loss: {val_loss:.6f} - val_AP: {val_ap:.6f} - val_samples: {val_items}"
        )

        if save_best_model_path and not np.isnan(val_ap) and val_ap > best_val_ap:
            best_val_ap = val_ap
            best_epoch = epoch
            torch.save(
                {
                    'epoch': epoch,
                    'val_ap': float(val_ap),
                    'model_state_dict': model.state_dict(),
                },
                save_best_model_path,
            )
            print(
                f"  saved best checkpoint by val_AP={val_ap:.6f} "
                f"to: {save_best_model_path}"
            )

        if use_early_stopping and epoch >= early_stopping_min_epochs and epoch_items > 0:
            monitor_metric = val_ap if not np.isnan(val_ap) else train_ap
            if np.isnan(monitor_metric):
                print("  early-stopping skipped: AP metric is NaN")
                continue

            # Monitorujeme AP (cim vyssi, tim lepsi).
            should_stop = early_stopper.step(monitor_metric)
            best_metric = early_stopper.best_score
            wait = early_stopper.counter
            print(
                "  early-stopping status: "
                f"best_AP={best_metric:.6f}, "
                f"wait={wait}/{early_stopping_patience}"
            )
            if should_stop:
                print(f"Early stopping triggered at epoch {epoch}.")
                break

    if save_best_model_path:
        if best_epoch is None:
            print(
                "Best checkpoint was not saved because validation AP was NaN "
                "in all epochs."
            )
        else:
            print(
                f"Best checkpoint summary: epoch={best_epoch}, "
                f"val_AP={best_val_ap:.6f}, path={save_best_model_path}"
            )

    return model


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Train GNN directly from graph batches manifest (RAM-safe streaming).'
    )
    parser.add_argument(
        '--graph-manifest',
        default='binding_site_graph_batches/manifest.json',
        help='Path to manifest.json generated by binding_site_graph.py',
    )
    parser.add_argument('--epochs', type=int, default=5)
    parser.add_argument('--batch-size', type=int, default=4)
    parser.add_argument('--lr', type=float, default=1e-4)
    parser.add_argument('--hidden-dim', type=int, default=256)
    parser.add_argument('--num-heads', type=int, default=4)
    parser.add_argument('--dropout', type=float, default=0.5)
    parser.add_argument('--num-classes', type=int, default=2)
    parser.add_argument('--device', default=None)
    parser.add_argument(
        '--val-manifest',
        default=None,
        help='Optional manifest.json for validation set (if omitted, uses --val-ratio split).',
    )
    parser.add_argument(
        '--val-ratio',
        type=float,
        default=0.2,
        help='Validation file ratio when --val-manifest is not provided.',
    )
    parser.add_argument(
        '--split-seed',
        type=int,
        default=42,
        help='Random seed for train/validation split from manifest files.',
    )
    parser.add_argument(
        '--early-stopping-patience',
        type=int,
        default=0,
        help='Enable early stopping with given patience (0 disables).',
    )
    parser.add_argument(
        '--early-stopping-min-delta',
        type=float,
        default=0.0,
        help='Minimum improvement in monitored score to reset patience.',
    )
    parser.add_argument(
        '--early-stopping-min-epochs',
        type=int,
        default=1,
        help='Do not apply early stopping before this epoch.',
    )
    parser.add_argument('--save-model', default='gnn_model.pt')
    parser.add_argument(
        '--save-best-model',
        default='gnn_model_best.pt',
        help='Path to best checkpoint saved by validation AP (set empty string to disable).',
    )
    args = parser.parse_args()

    if not os.path.exists(args.graph_manifest):
        raise FileNotFoundError(f"Manifest not found: {args.graph_manifest}")

    model = train_from_manifest(
        manifest_path=args.graph_manifest,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        hidden_dim=args.hidden_dim,
        num_heads=args.num_heads,
        dropout=args.dropout,
        num_classes=args.num_classes,
        device=args.device,
        early_stopping_patience=args.early_stopping_patience,
        early_stopping_min_delta=args.early_stopping_min_delta,
        early_stopping_min_epochs=args.early_stopping_min_epochs,
        val_manifest_path=args.val_manifest,
        val_ratio=args.val_ratio,
        split_seed=args.split_seed,
        save_best_model_path=(args.save_best_model if args.save_best_model else None),
    )

    torch.save(model.state_dict(), args.save_model)
    print(f"Saved model to: {args.save_model}")